language: node_js
node_js:
  - '0.11'
  - '0.10'
install:
  - npm update npm -g
  - npm install
script:  
  - make test-coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose